logging:
  level: INFO

openApi:
  name: SIM admin
  description: SIM administration service
  termsOfService: http://example.org
  contactEmail: rmz@telenordigital.com
  resourcePackage: org.ostelco

hlrs:
  - name: Loltel
    endpoint: ${WG2_ENDPOINT}
    userId: ${WG2_USER}
    apiKey: ${WG2_API_KEY}

profileVendors:
  - name: Idemia
    endpoint: ${ES2PLUS_ENDPOINT}
    requesterIdentifier: ${FUNCTION_REQUESTER_IDENTIFIER}

# Note, list must end with a wildcard match
phoneTypes:
  - regex: "android.*"
    profile: ANDROID_PROFILE_1
  - regex: "iphone.*"
    profile: IPHONE_PROFILE_1
  - regex: ".*"
    profile: IPHONE_PROFILE_2

database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}

httpClient:
  minThreads: 1
  maxThreads: 128
  gzipEnabled: true
  gzipEnabledForRequests: true
  timeout: 10000ms
  tls:
    # Default is 500 milliseconds, we need more when debugging.
    # protocol: TLSv1.2
    keyStoreType: JKS
    keyStorePath: /certs/idemia-client-cert.jks
    keyStorePassword: foobar
    verifyHostname: false
    trustSelfSignedCertificates: true
