apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaninfo-shredder
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  scaninfo-shredder
            image: eu.gcr.io/pantel-2decb/scaninfo-shredder:SHREDDER_VERSION
            imagePullPolicy: Always
            env:
            - name: DATASET_PROJECT
              value: pantel-2decb
            - name: DATASTORE_NAMESPACE
              value: dev
            - name: JUMIO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jumio-secrets
                  key: apiToken
            - name: JUMIO_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: jumio-secrets
                  key: apiSecret
          restartPolicy: Never
