version: "3.5"

services:
  prime:
    container_name: prime
    build: prime
    ports:
      - "8082:8082"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/pantel-prod.json
    networks:
      net:
        aliases:
          - prime
        ipv4_address: 172.16.238.4

  ocsgw:
    container_name: ocsgw
    build: ocsgw
    ports:
      - "3868:3868"
    depends_on:
      - "prime"
    command: ["./wait_for_prime.sh"]

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24