version: "3.3"

services:
  ocsgw:
    container_name: ocsgw
    build: ocsgw
    environment:
      - SERVICE_FILE=pantel-prod.json
      - GOOGLE_CLOUD_PROJECT=pantel-2decb
    volumes:
      - ./ocsgw/cert:/cert/
      - ./ocsgw/config:/config/
  auth-server:
    container_name: auth-server
    build: auth-server
    ports:
      - "8080:8080"
