version: "3.7"

services:
  prime:
    container_name: prime
    build:
      context: prime
      dockerfile: Dockerfile.test
    environment:
    - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    - FIREBASE_ROOT_PATH=test
    - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
    - PUBSUB_PROJECT_ID=${GCP_PROJECT_ID}
    - JUMIO_API_TOKEN=
    - JUMIO_API_SECRET=
    - STRIPE_API_KEY=${STRIPE_API_KEY}
    - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    - DATASTORE_EMULATOR_HOST=localhost:9090
    - DATASTORE_PROJECT_ID=${GCP_PROJECT_ID}
    - LOCAL_TESTING=true
    ports:
    - "9090:8080"
    - "8082:8082"
    depends_on:
    - "pubsub-emulator"
    - "neo4j"
    command: ["/bin/bash", "./wait.sh"]
    tmpfs:
      - /data
    networks:
      net:
        aliases:
        - "prime"
        ipv4_address: 172.16.238.5
      default:

  esp:
    container_name: esp
    image: gcr.io/endpoints-release/endpoints-runtime:1
    volumes:
    - "./prime/config:/esp"
    - "./certs/ocs.dev.ostelco.org:/etc/nginx/ssl"
    command: >
      --service=ocs.dev.ostelco.org
      --rollout_strategy=managed
      --http2_port=80
      --ssl_port=443
      --backend=grpc://172.16.238.5:8082
      --service_account_key=/esp/pantel-prod.json
    networks:
      net:
        aliases:
        - "ocs.dev.ostelco.org"
        ipv4_address: 172.16.238.4
      default:

  metrics-esp:
    container_name: metrics-esp
    image: gcr.io/endpoints-release/endpoints-runtime:1
    volumes:
    - "./prime/config:/esp"
    - "./certs/metrics.dev.ostelco.org:/etc/nginx/ssl"
    command: >
      --service=metrics.dev.ostelco.org
      --rollout_strategy=managed
      --http2_port=80
      --ssl_port=443
      --backend=grpc://172.16.238.5:8083
      --service_account_key=/esp/pantel-prod.json
    networks:
      net:
        aliases:
        - "metrics.dev.ostelco.org"
        ipv4_address: 172.16.238.6
      default:

  ocsgw:
    container_name: ocsgw
    build: ocsgw
    depends_on:
    - "prime"
    command: ["./wait.sh"]
    environment:
    - OCS_GRPC_SERVER=ocs.dev.ostelco.org
    - METRICS_GRPC_SERVER=metrics.dev.ostelco.org
    - SERVICE_FILE=pantel-prod.json
    - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
    - DIAMETER_CONFIG_FILE=server-jdiameter-config.xml
    - OCS_DATASOURCE_TYPE=Local
    - CONFIG_FOLDER=/config/
    - "JAVA_OPTS=-Xms512m -Xmx1024m -server"
    volumes:
    - ./ocsgw/cert:/cert/
    - ./ocsgw/config:/config/
    networks:
      net:
        aliases:
        - "ocsgw"
        ipv4_address: 172.16.238.3

  neo4j:
    container_name: "neo4j"
    image: neo4j:3.4.9
    environment:
    - NEO4J_AUTH=none
    ports:
    - "7687:7687"
    - "7474:7474"
    tmpfs: "/data"

  pubsub-emulator:
    container_name: pubsub-emulator
    image: knarz/pubsub-emulator

  datastore-emulator:
    container_name: datastore-emulator
    image: google/cloud-sdk:218.0.0
    expose:
    - "8081"
    environment:
    - CLOUDSDK_CORE_PROJECT=${GCP_PROJECT_ID}
    - DATASTORE_DATASET=${GCP_PROJECT_ID}
    command: ["gcloud", "beta", "emulators", "datastore", "start", "--host-port=0.0.0.0:8081"]


networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
