version: "3.3"

services:
  ext-pgw:
    container_name: ext-pgw
    build: ext-pgw
    networks:
      net:
        aliases:
          - ext-pgw
        ipv4_address: 172.16.238.2
    depends_on:
      - "ocsgw"
    command: ["./wait_for_ocsgw.sh"]
