version: "3.3"

services:
  ocsgw:
    environment:
    - OCS_GRPC_SERVER=ocs.dev.ostelco.org
    - METRICS_GRPC_SERVER=metrics.dev.ostelco.org
    extra_hosts:
    - "ocs.dev.ostelco.org:35.190.197.222"
    - "api.dev.ostelco.org:35.190.192.27"
    - "metrics.dev.ostelco.org:146.148.16.201"
    network_mode: "host"