logging:
  level: INFO


hlrs:
  - name: Foo
    hlrType: WG2
    hssNameUsedInAPI: foo
    endpoint: http://localhost:9180/default/provision
    userId: user
    apiKey: xyz
  - name: Bar
    hlrType: Dummy

httpClient:
  timeout: 10000ms
