services:
  - type: firebase
    config:
      configFile: src/integration-tests/resources/pantel-tests.json
      databaseName: pantel-tests
  - type: api
  - type: admin

eventProcessor:
  configFile: src/integration-tests/resources/pantel-tests.json
  projectId: pantel-tests
  topicId: data-traffic

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
