modules:
  - type: firebase
    config:
      configFile: config/pantel-prod.json
      databaseName: pantel-2decb
      rootPath: test
  - type: ocs
    config:
      projectId: pantel-2decb
      topicId: data-traffic
  - type: api
    namespace: https://ostelco
  - type: admin

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
