version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
    - image: circleci/openjdk:8u171-jdk-browsers

    steps:
    - setup_remote_docker
    - checkout
    - restore_cache:
        keys:
          - gradle-cache
    - run:
        name: gradle build prime. docker build and push prime.
        command: |
          ./gradlew clean prime:build
          PROJECT_ID="pantel-tests"
          PRIME_VERSION="$(./gradlew prime:properties -q | grep "version:" | awk '{print $2}' | tr -d '[:space:]')"
          echo docker build --tag=gcr.io/$PROJECT_ID/prime:$PRIME_VERSION prime
          echo docker push --tag=gcr.io/$PROJECT_ID/prime:$PRIME_VERSION
          rm -f gradle/caches/modules-2/modules-2.lock
          rm -rf .gradle/caches/*/plugin-resolution/
    - save_cache:
        key: gradle-cache
        paths:
        - "~/.gradle/caches"
#  deploy-prime:
#    docker:
#    - image: devth/helm:v2.9.1
#    working_directory: ~/repo
#    steps:
#    - run:
#        name: running helm install
#        command: |
#          echo $GOOGLE_CREDENTIALS > $HOME/pantel-tests.json
#          gcloud auth activate-service-account --key-file=$HOME/pantel-tests.json
#          gcloud container clusters get-credentials my-cluster --zone europe-west2-c --project pantel-tests
#          kubectl create serviceaccount -n kube-system tiller
#          kubectl create clusterrolebinding tiller-binding --clusterrole=cluster-admin --serviceaccount kube-system:tiller
#          helm init --service-account tiller
#          helm repo add pantel-tests https://pantel-tests-charts.storage.googleapis.com/
#          helm install pantel-tests/prime --name prime --set firebaseServiceAccount=$(echo $FIREBASE_SERVICE_ACCOUNT | base64)
workflows:
  version: 2
  my-workflow:
    jobs:
    - build:
#      filters:
#        branches:
#          only:
#          - master