services:
  - type: firebase
    config:
      configFile: /secret/pantel-prod.json
      databaseName: pantel-2decb
  - type: api
  - type: admin

eventProcessor:
  configFile: /secret/pantel-prod.json
  projectId: pantel-2decb
  topicId: data-traffic

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
  appenders:
    - type: console
      layout:
        type: json

