modules:
  - type: firebase
    config:
      configFile: /secret/pantel-prod.json
      databaseName: pantel-2decb
      rootPath: v2
  - type: ocs
    config:
      projectId: pantel-2decb
      topicId: data-traffic
  - type: api
    config:
      secret: "change_me"
  - type: admin

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
  appenders:
    - type: console
      layout:
        type: json

