# This config is used as config.yaml when prime is running using docker-compose for Acceptance Testing

modules:
  - type: firebase
    config:
      configFile: /secret/pantel-prod.json
      databaseName: pantel-2decb
      rootPath: test
  - type: ocs
    config:
      projectId: pantel-2decb
      topicId: data-traffic
  - type: api
    config:
      secret: "change_me"
      authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
  - type: admin

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
