# This config is used as config.yaml when prime is running using docker-compose for Acceptance Testing

modules:
- type: jersey
  config:
    authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
    jerseyClient:
      timeout: 3s
      connectionRequestTimeout: 1s
- type: firebase
  config:
    configFile: /secret/pantel-prod.json
    rootPath: test
- type: Imei-lookup
  config:
    csvFile: /config-data/imeiDb.csv
- type: neo4j
  config:
    host: neo4j
    protocol: bolt
- type: analytics
  config:
    projectId: pantel-2decb
    dataTrafficTopicId: data-traffic
    purchaseInfoTopicId: purchase-info
    activeUsersTopicId: active-users
- type: ocs
  config:
    lowBalanceThreshold: 0
- type: pseudonymizer
  config:
    datastoreType: emulator
- type: api
- type: stripe-payment-processor
- type: firebase-app-notifier
  config:
    configFile: /secret/pantel-prod.json
- type: admin
- type: graphql
- type: scaninfo-store
  config:
    storeType: emulator
server:
  applicationConnectors:
  - type: h2c
    port: 8080
    maxConcurrentStreams: 1024
    initialStreamRecvWindow: 65535

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
    # suppress exception logged while connecting to real bigQuery 3 times before connecting to emulator
    com.google.auth.oauth2.ComputeEngineCredentials: ERROR