#
#  To start this job, do 
#    kubectl create -f ./cronjob.yaml
#  https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
#

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: preallocate-sim-profiles
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: preallocate-sim-profiles
            image: busybox-curl
            args:
            - /bin/sh
            - -c
            - date; echo Triggering sim preallocation
	    - curl http://prime:8081/tasks/preallocate_sim_profiles
          restartPolicy: OnFailure
