logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG

# Database settings
database:
  # the name of your JDBC driver
  driverClass: org.sqlite.JDBC

  # the JDBC URL
  url: jdbc:sqlite:sim_inventory.db

httpClient:

  # The minimum number of threads to use for asynchronous calls.
  minThreads: 1

  # The maximum number of threads to use for asynchronous calls.
  maxThreads: 128

  # If true, the client will automatically decode response entities
  # with gzip content encoding.
  gzipEnabled: true

  # If true, the client will encode request entities with gzip
  # content encoding. (Requires gzipEnabled to be true).
  gzipEnabledForRequests: true

server:
  applicationConnectors:
    - type: h2
      port: 8445
      maxConcurrentStreams: 1024
      initialStreamRecvWindow: 65535
      keyStorePath: KeyStore.jks
      keyStorePassword: secret
      trustStorePath: TrustStore.jks
      trustStorePassword: secret
      supportedCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256