type: google.api.Service

config_version: 3

name: metrics.oya.world

title: Prime Metrics Reporter Service gRPC API

apis:
  - name: org.ostelco.prime.metrics.api.OcsgwAnalyticsService

usage:
  rules:
  # All methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: prime-service-account@GCP_PROJECT_ID.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/prime-service-account@GCP_PROJECT_ID.iam.gserviceaccount.com
    audiences: >
      https://metrics.oya.world/org.ostelco.prime.metrics.api.OcsgwAnalyticsService,
      metrics.oya.world/org.ostelco.prime.metrics.api.OcsgwAnalyticsService,
      metrics.oya.world
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account