swagger: "2.0"
info:
  title: "Ostelco API"
  description: "The client API for Panacea."
  version: "1.0.0"
host: "prod-api.new.dev.ostelco.org"
x-google-endpoints:
  - name: "prod-api.new.dev.ostelco.org"
    allowCors: true
schemes:
  - "https"
paths:
  "/profile":
    get:
      description: "Get profile for the user (email-id present in the bearer token)."
      produces:
        - application/json
      operationId: "getProfile"
      responses:
        200:
          description: "Get the profile for this user."
          schema:
            $ref: '#/definitions/Profile'
        404:
          description: "Profile not found."
      security:
        - auth0_jwt: []
    post:
      description: "Create a new profile."
      consumes:
        - application/json
      produces:
        - application/json
      operationId: "createProfile"
      parameters:
        - name: profile
          in: body
          description: The profile to create.
          schema:
            $ref: '#/definitions/Profile'
        - name: referred_by
          in: query
          description: "Referral ID of user who has invited this user"
          type: string
      responses:
        201:
          description: "Successfully created the profile."
          schema:
              $ref: '#/definitions/Profile'
        400:
          description: "Incomplete profile"
        403:
          description: "Profile invalid or already created"
        502:
          description: "Failed to store profile"
      security:
        - auth0_jwt: []
    put:
      description: "Update an existing profile."
      consumes:
        - application/json
      produces:
        - application/json
      operationId: "updateProfile"
      parameters:
        - in: body
          name: profile
          description: The updated profile.
          schema:
            $ref: '#/definitions/Profile'
      responses:
        200:
          description: "Successfully updated the profile."
          schema:
              $ref: '#/definitions/Profile'
        400:
           description: "Incomplete profile"
        404:
          description: "Profile not found."
        502:
          description: "Failed to store profile"
      security:
        - auth0_jwt: []
  "/applicationtoken":
    post:
      description: "Store application token"
      consumes:
        - application/json
      produces:
        - application/json
      operationId: "storeApplicationToken"
      parameters:
        - name: applicationToken
          in: body
          description: application token
          schema:
            $ref: '#/definitions/ApplicationToken'
      responses:
        201:
          description: "Successfully stored token."
          schema:
            $ref: '#/definitions/ApplicationToken'
        400:
          descripton: "Token malformed. Not able to store"
        404:
          description: "User not found."
        507:
          description: "Not able to store token."
      security:
        - auth0_jwt: []
  "/paymentSources":
    get:
      description: "Get all payment sources for the user."
      produces:
        - application/json
      operationId: "listSources"
      responses:
        200:
          description: "List of payment sources."
          schema:
            $ref: '#/definitions/PaymentSourceList'
        404:
          description: "No user found."
        503:
          description: "Service Unavailable"
      security:
        - auth0_jwt: []
    post:
      description: "Add a new payment source for user"
      produces:
      - application/json
      operationId: "createSource"
      parameters:
      - name: sourceId
        in: query
        description: "The stripe-id of the source to be added to user"
        required: true
        type: string
      responses:
        201:
          description: "Successfully added source to user"
          schema:
            $ref: '#/definitions/PaymentSource'
        403:
          description: "Invalid source"
        404:
          description: "User not found."
        503:
          description: "Service Unavailable"
      security:
      - auth0_jwt: []
    put:
      description: "Set the source as default for user"
      produces:
      - application/json
      operationId: "setDefaultSource"
      parameters:
      - name: sourceId
        in: query
        description: "The stripe-id of the default source"
        required: true
        type: string
      responses:
        200:
          description: "Successfully set as default source to user"
          schema:
            $ref: '#/definitions/PaymentSource'
        403:
          description: "Invalid source"
        404:
          description: "User not found."
        503:
          description: "Service Unavailable"
      security:
      - auth0_jwt: []
    delete:
      description: "Remove a payment source for user"
      produces:
      - application/json
      operationId: "removeSource"
      parameters:
      - name: sourceId
        in: query
        description: "The stripe-id of the source to be removed"
        required: true
        type: string
      responses:
        200:
          description: "Successfully removed the source"
          schema:
            $ref: '#/definitions/PaymentSource'
        400:
          description: "The source could not be removed"
        403:
          description: "Invalid source"
        404:
          description: "No such source for user"
        503:
          description: "Service Unavailable"
      security:
      - auth0_jwt: []
  "/products":
    get:
      description: "Get all products for the user."
      produces:
        - application/json
      operationId: "getAllProducts"
      responses:
        200:
          description: "List of products."
          schema:
            $ref: '#/definitions/ProductList'
        404:
          description: "No products found for the user."
      security:
        - auth0_jwt: []
  "/products/{sku}/purchase":
    post:
      description: "Buy the product specified in sku parameter."
      produces:
      - application/json
      - text/plain
      operationId: "purchaseProduct"
      parameters:
      - name: sku
        in: path
        description: "SKU to be purchased"
        required: true
        type: string
      - name: sourceId
        in: query
        description: "The stripe-id of the source to be used for this purchase (if empty, use default source)"
        required: false
        type: string
      - name: saveCard
        in: query
        description: "Whether to save this card as a source for this user (default = false)"
        required: false
        type: boolean
      responses:
        201:
          description: "Successfully purchased the product."
          schema:
            $ref: '#/definitions/Product'
        404:
          description: "Product not found."
      security:
      - auth0_jwt: []
  "/purchases":
    get:
      description: "Get list of all purchases."
      produces:
      - application/json
      - text/plain
      operationId: "getPurchaseHistory"
      responses:
        200:
          description: "List of Purchase Records."
          schema:
            $ref: '#/definitions/PurchaseRecordList'
        403:
          description: "Not allowed to charge this source"
        404:
          description: "No Purchase Records found for the user."
        503:
          description: "Service Unavailable"
      security:
      - auth0_jwt: []
  "/subscriptions":
    get:
      description: "Get subscription (msisdn) for the user (identified by bearer token)."
      produces:
      - application/json
      operationId: "getSubscriptions"
      responses:
        200:
          description: "Get subscriptions for this user."
          schema:
            $ref: '#/definitions/SubscriptionList'
        404:
          description: "No subscription found for this user."
      security:
      - auth0_jwt: []
  "/bundles":
    get:
      description: "Get bundles (balance) for the user (identified by bearer token)."
      produces:
        - application/json
      operationId: "getBundles"
      responses:
        200:
          description: "Get bundles for this user."
          schema:
            $ref: '#/definitions/BundleList'
        404:
          description: "No bundle found for this user."
      security:
        - auth0_jwt: []
  "/subscription/activePseudonyms":
    get:
      description: "Get currently active pseudonyms for the user's msisdn (identified by bearer token)."
      produces:
        - application/json
      operationId: "getActivePseudonyms"
      responses:
        200:
          description: "Get active pseudonyms for the user's msisdn."
          schema:
            $ref: '#/definitions/ActivePseudonyms'
        404:
          description: "No subscription found for this user."
      security:
        - auth0_jwt: []
  "/referred":
    get:
      description: "Get list of people whom the user has referred to."
      produces:
        - application/json
      operationId: "getReferred"
      responses:
        200:
          description: "List of people whom this person has referred to."
          schema:
            $ref: '#/definitions/PersonList'
        404:
          description: "No referrals found for this user."
      security:
        - auth0_jwt: []
  "/referred/by":
    get:
      description: "Get the people who had referred this user."
      produces:
      - application/json
      operationId: "getReferredBy"
      responses:
        200:
          description: "List of people whom this person has referred to."
          schema:
            $ref: '#/definitions/Person'
        404:
          description: "No 'referred by' found for this user."
      security:
      - auth0_jwt: []
  "/consents":
    get:
      description: "Get all consents for the user."
      produces:
        - application/json
      operationId: "getConsents"
      responses:
        200:
          description: "List of consents."
          schema:
            $ref: '#/definitions/ConsentList'
        404:
          description: "No consents found for the user."
      security:
        - auth0_jwt: []
  "/consents/{consent-id}":
    put:
      description: "Change the value for the specified consent."
      operationId: "updateConsent"
      responses:
        200:
          description: "Successfully updated the consent."
        404:
          description: "Consent not found."
      security:
        - auth0_jwt: []
      parameters:
      - name: consent-id
        in: path
        description: "Id of the consent to be changed"
        required: true
        type: string
      - name: accepted
        in: query
        description: "Whether user accepted the consent (default = true)"
        required: false
        type: boolean
  "/graphql":
    post:
      description: "GraphQL endpoint"
      consumes:
      - application/json
      produces:
      - application/json
      operationId: "graphql"
      responses:
        200:
          description: "Success"
          schema:
            type: object
        404:
          description: "Not found"
      security:
      - auth0_jwt: []
      parameters:
      - name: "request"
        in: body
        description: "GraphQL Request."
        schema:
          $ref: '#/definitions/GraphQLRequest'

definitions:
  Profile:
    type: object
    properties:
      name:
        type: string
      address:
        type: string
      postCode:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
        format: email
      referralId:
        type: string
    required:
      - email
  SubscriptionList:
    type: array
    items:
      $ref: '#/definitions/Subscription'
  Subscription:
    type: object
    properties:
      msisdn:
        description: "Mobile number for this subscription"
        type: string
      alias:
        description: "Human readable optional alias for this subscription"
        type: string
  BundleList:
    type: array
    items:
      $ref: '#/definitions/Bundle'
  Bundle:
    type: object
    properties:
      id:
        description: "Bundle ID"
        type: string
      balance:
        description: "Balance units in this bundle"
        type: integer
        format: int64
  PurchaseRecordList:
    type: array
    items:
      $ref: '#/definitions/PurchaseRecord'
  PurchaseRecord:
    type: object
    properties:
      id:
        description: "Purchase Record ID"
        type: string
      msisdn:
        description: "Deprecated: The MSISDN for which the purchase was made."
        type: string
      timestamp:
        description: "The time stamp of the purchase"
        type: integer
        format: int64
      product:
        $ref: '#/definitions/Product'
    required:
      - timestamp
      - product
  ProductList:
    type: array
    items:
        $ref: '#/definitions/Product'
  Product:
    type: object
    properties:
      sku:
        description: "A unique Id representing a SKU"
        type: string
      price:
        $ref: '#/definitions/Price'
      properties:
        type: object
      presentation:
        type: object
    required:
      - sku
      - price
  PaymentSourceList:
    type: array
    items:
        $ref: '#/definitions/PaymentSource'
  PaymentSource:
    type: object
    properties:
      id:
        description: "The identifier for the source"
        type: string
      type:
        description: "The type of source"
        type: string
      details:
        description: "All information stored with the source"
        type: object
        additionalProperties: true
    required:
      - id
      - type
  ConsentList:
    type: array
    items:
        $ref: '#/definitions/Consent'
  Consent:
    type: object
    properties:
      consentId:
        description: "The identifier of the consent"
        type: string
      description:
        description: "A description of the consent"
        type: string
      accepted:
        description: "Whether user has accepted the consent or not"
        type: boolean
  Price:
    type: object
    properties:
      amount:
        description: "A positive integer in the smallest currency unit"
        type: integer
        minimum: 0
      currency:
        description: "ISO 4217 currency code (three letter alphabetic code)"
        type: string
    required:
      - amount
      - currency
  ApplicationToken:
    type: object
    properties:
      token:
        description: "Application token"
        type: string
      applicationID:
        description: "Uniquely identifier for the app instance"
        type: string
      tokenType:
        description: "Type of application token (FCM)"
        type: string
    required:
      - token
      - applicationID
  PseudonymEntity:
    type: object
    properties:
      sourceId:
        type: string
      pseudonym:
        type: string
      start:
        description: "The start time stamp for this pseudonym"
        type: integer
        format: int64
      end:
        description: "The start time stamp for this pseudonym"
        type: integer
        format: int64
    required:
      - sourceId
      - pseudonym
      - start
      - end
  Person:
    type: object
    properties:
      name:
        type: string
    required:
      - name
  PersonList:
    type: array
    items:
      $ref: '#/definitions/Person'
  ActivePseudonyms:
    type: object
    properties:
      current:
        $ref: '#/definitions/PseudonymEntity'
      next:
        $ref: '#/definitions/PseudonymEntity'
    required:
      - current
      - next
  GraphQLRequest:
    type: object
    properties:
      query:
        description: "GraphQL query."
        type: string
      operationName:
        description: "GraphQL Operation Name."
        type: string
      variables:
        description: "GraphQL query variables."
        type: object
securityDefinitions:
  auth0_jwt:
    authorizationUrl: "https://ostelco.eu.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://ostelco.eu.auth0.com/"
    x-google-jwks_uri: "https://ostelco.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "http://google_api"