version: "3.7"

services:
  ocsgw:
    container_name: ocsgw
    build: .
    command: ["./start_dev.sh"]
    environment:
      - OCS_GRPC_SERVER=ocs.dev.oya.world
      - METRICS_GRPC_SERVER=metrics.dev.oya.world
      - SERVICE_FILE=prime-service-account.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - PUBSUB_PROJECT_ID=${GCP_PROJECT_ID}
      - PUBSUB_CCR_TOPIC_ID=ocs-ccr
      - PUBSUB_CCA_TOPIC_ID=ocs-cca
      - PUBSUB_CCA_SUBSCRIPTION_ID=ocsgw-cca-sub
      - PUBSUB_ACTIVATE_SUBSCRIPTION_ID=ocsgw-activate-sub
    volumes:
      - ./config:/config/