hlrs:
  - name: loltel
    endpoint: ${WG2_ENDPOINT}
    userId: ${WG2_USER}
    apiKey: ${WG2_API_KEY}

httpClient:
  timeout: 10000ms

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
    org.dhatim.dropwizard.prometheus.DropwizardMetricsExporter: ERROR
