swagger: "2.0"
info:
  title: "Houston Admin API"
  description: "The APIs for the Houston Admin Client."
  version: "1.0.0"
host: "houston-api.dev.ostelco.org"
x-google-endpoints:
  - name: "houston-api.dev.ostelco.org"
    allowCors: true
schemes:
  - "https"
paths:
  "/profile/email/{email}":
    get:
      description: "Get profile for the given email-id (url encoded)."
      produces:
      - application/json
      operationId: "getProfileByEmail"
      responses:
        200:
          description: "Get the profile for this user."
          schema:
            $ref: '#/definitions/Profile'
        404:
          description: "Profile not found."
      security:
      - auth0_jwt: []
  "/profile/msisdn/{msisdn}":
    get:
      description: "Get profile for the given msisdn."
      produces:
      - application/json
      operationId: "getProfileByMsisdn"
      responses:
        200:
          description: "Get the profile for this user."
          schema:
            $ref: '#/definitions/Profile'
        404:
          description: "Profile not found."
      security:
      - auth0_jwt: []
definitions:
  Profile:
    type: object
    properties:
      name:
        type: string
      address:
        type: string
      postCode:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
        format: email
      referralId:
        type: string
    required:
    - email
  SubscriptionList:
    type: array
    items:
      $ref: '#/definitions/Subscription'
  Subscription:
    type: object
    properties:
      msisdn:
        description: "Mobile number for this subscription"
        type: string
      alias:
        description: "Human readable optional alias for this subscription"
        type: string
  BundleList:
    type: array
    items:
      $ref: '#/definitions/Bundle'
  Bundle:
    type: object
    properties:
      id:
        description: "Bundle ID"
        type: string
      balance:
        description: "Balance units in this bundle"
        type: integer
        format: int64
  PurchaseRecordList:
    type: array
    items:
      $ref: '#/definitions/PurchaseRecord'
  PurchaseRecord:
    type: object
    properties:
      id:
        description: "Purchase Record ID"
        type: string
      msisdn:
        description: "Deprecated: The MSISDN for which the purchase was made."
        type: string
      timestamp:
        description: "The time stamp of the purchase"
        type: integer
        format: int64
      product:
        $ref: '#/definitions/Product'
    required:
    - timestamp
    - product
    - end
securityDefinitions:
  auth0_jwt:
    authorizationUrl: "https://redotter-admin-dev.eu.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://redotter-admin-dev.eu.auth0.com/"
    x-google-jwks_uri: "https://redotter-admin-dev.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "http://google_api"