swagger: "2.0"
info:
  title: "Houston Admin API"
  description: "The APIs for the Houston Admin Client."
  version: "1.0.0"
host: "houston-api.dev.ostelco.org"
x-google-endpoints:
  - name: "houston-api.dev.ostelco.org"
    allowCors: true
schemes:
  - "https"
paths:
  "/pseudonym/current/{msisdn}":
    get:
      description: "Get the pseudonym which is valid at the time of the call."
      produces:
      - application/json
      operationId: "getPseudonym"
      responses:
        200:
          description: "pseudonym for this msisdn."
          schema:
            $ref: '#/definitions/PseudonymEntity'
        404:
          description: "Not found."
      security:
      - auth0_jwt: []
      parameters:
      - name: msisdn
        in: path
        description: msisdn to be pseudonymised
        required: true
        type: string
definitions:
  PseudonymEntity:
    type: object
    properties:
      sourceId:
        type: string
      pseudonym:
        type: string
      start:
        description: "The start time stamp for this pseudonym"
        type: integer
        format: int64
      end:
        description: "The start time stamp for this pseudonym"
        type: integer
        format: int64
    required:
    - sourceId
    - pseudonym
    - start
    - end
securityDefinitions:
  auth0_jwt:
    authorizationUrl: "https://redotter-admin-dev.eu.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://redotter-admin-dev.eu.auth0.com/"
    x-google-jwks_uri: "https://redotter-admin-dev.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "http://google_api"