version: "3.7"

services:
  dataflow-pipelines:
    container_name: dataflow-pipelines
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/prime-service-account.json
      - PROJECT=${GCP_PROJECT_ID}
      - JOB_NAME=data-traffic
      - PUBSUB_TOPIC=data-traffic
      - DATASET=data_consumption
      - UPDATING=true