logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
  appenders:
    - type: console
      layout:
        type: json
        customFieldNames:
           level: severity

bqmetrics:
  - type: summary
    name: active_users
    help: Number of active users
    resultColumn: count
    sql: >
        SELECT count(distinct user_pseudo_id) AS count FROM `pantel-2decb.analytics_160712959.events_*`
        WHERE event_name = "first_open"
        LIMIT 1000
  - type: summary
    name: sims_who_have_used_data
    help: Number of SIMs that has used data last 24 hours
    resultColumn: count
    sql: >
        SELECT count(DISTINCT msisdn) FROM `pantel-2decb.data_consumption.raw_consumption`
        WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
  - type: summary
    name: total_data_used
    help: Total data used last 24 hours
    resultColumn: count
    sql: >
        SELECT sum(bucketBytes) FROM `pantel-2decb.data_consumption.raw_consumption`
        WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
