apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bq-metrics-extractor
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  bq-metrics-extractor
            image: eu.gcr.io/GCP_PROJECT_ID/bq-metrics-extractor:EXTRACTOR_VERSION
            imagePullPolicy: Always
            env:
              - name: DATASET_PROJECT
                value: GCP_PROJECT_ID
          restartPolicy: Never
