#
# To start this job, do
#    kubectl create -f ./cronjob.yaml
# https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
# TODO: sync with prime.yaml

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: monitor-stripe
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stripe-monitor
            image: gcr.io/gcp-runtimes/ubuntu_18_0_4
            env:
              - name: STRIPE_EVENTS
                value: '["customer.deleted", "customer.created", "charge.succeeded", "charge.refunded"]'
              - name: INTERVAL
                value: "-7200"        # Time interval in seconds
            command: ["/bin/sh", "-c"]
            args:
              - echo Checking Stripe;
                date;
                curl -vvv -sS http://prime-monitor-service:8080/stripe/monitor/apiversion 2>&1;
                curl -vvv -sS http://prime-monitor-service:8080/stripe/monitor/webhook/enabled 2>&1;
                echo Check done;
          restartPolicy: OnFailure
