logging:
#  level: ALL
   level: INFO

simBatchData: sample-sim-batch-for-sm-dp+.csv

openApi:
  name: SM-DP-emulator
  description: Test fixture simulating ES2+ interactions of an SM-DP+
  termsOfService: http://example.org
  contactEmail: rmz@telenordigital.com
  resourcePackage: org.ostelco

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      # Enabling conscrypt blows the whole thing up, so don't do that.
      #jceProvider: Conscrypt
      keyStoreType: JKS
      keyStorePath: sk_keys.jks
      keyStorePassword: superSecreet
      validateCerts: false




httpClient:
  tls:
    protocol: TLSv1.2
    keyStoreType: JKS
    keyStorePath: sk_keys.jks
    keyStorePassword: superSecreet
#    validateCerts: false
#    keyStorePath: sk_keys.jks
#    keyStorePassword: superSecreet
#    keyStoreType: JKS
#    trustStorePath: sk_trust.jks
#    trustStorePassword: superSecreet
#    trustStoreType: JKS
    verifyHostname: false
    trustSelfSignedCertificates: true
