logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG


simBatchData: sample-sim-batch-for-sm-dp+.csv

openApi:
  name: SM-DP-emulator
  description: Test fixture simulating ES2+ interactions of an SM-DP+
  termsOfService: http://example.org
  contactEmail: rmz@telenordigital.com
  resourcePackage: org.ostelco

httpClient:

  # The minimum number of threads to use for asynchronous calls.
  minThreads: 1

  # The maximum number of threads to use for asynchronous calls.
  maxThreads: 128

  # If true, the client will automatically decode response entities
  # with gzip content encoding.
  gzipEnabled: true

  # If true, the client will encode request entities with gzip
  # content encoding. (Requires gzipEnabled to be true).
  gzipEnabledForRequests: true

