logging:
  level: ALL

simBatchData: sample-sim-batch-for-sm-dp+.csv

openApi:
  name: SM-DP-emulator
  description: Test fixture simulating ES2+ interactions of an SM-DP+
  termsOfService: http://example.org
  contactEmail: rmz@telenordigital.com
  resourcePackage: org.ostelco

#httpClient:
#
#  # The minimum number of threads to use for asynchronous calls.
#  minThreads: 1
#
#  # The maximum number of threads to use for asynchronous calls.
#  maxThreads: 128
#
#  # If true, the client will automatically decode response entities
#  # with gzip content encoding.
#  gzipEnabled: true
#
#  # If true, the client will encode request entities with gzip
#  # content encoding. (Requires gzipEnabled to be true).
#  gzipEnabledForRequests: true


# Maybe this can help https://stackoverflow.com/questions/35002780/setting-up-ssl-in-dropwizard
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: sk_keys.jks
      keyStorePassword: superSecreet
      validateCerts: false

#    jceProvider: Conscrypt
# keyStoreType: JKS
# keyStorePath: ../certificate-authority-simulated/crypto-artefacts/sm-dp-plus/keystore.jks
# keyStorePassword: superSecreet
#    keyStorePath: ../certificate-authority-simulated/crypto-artefacts/sm-dp-plus/sk_keys.jks
#    keyStorePassword: superSecreet
#      keyStoreType: JKS
#      keyStorePath: example.keystore
#      keyStorePassword: example
    # keyStorePassword: superSecreet
    #trustStorePath: ../certificate-authority-simulated/crypto-artefacts/sm-dp-plus/sk_trust.jks
    #trustStorePassword: superSecreet
      #certAlias: sm-dp-plus_sk.crt
      #validateCerts: false
      #validatePeers: false



# server:
#  adminMinThreads: 1
#  adminMaxThreads: 64
#  adminContextPath: /
#  applicationContextPath: /
#  applicationConnectors:
#    - type: http
#      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: sk_keys.jks
#      keyStorePassword: superSecreet
#      validateCerts: false

httpClient:
  tls:
    protocol: TLSv1.2
#    keyStorePath: sk_keys.jks
#    keyStorePassword: superSecreet
#    keyStoreType: JKS
#    trustStorePath: sk_trust.jks
#    trustStorePassword: superSecreet
#    trustStoreType: JKS
    verifyHostname: false
    trustSelfSignedCertificates: true
#    supportedProtocols: TLSv1.2, TLSv1.1
#     supportedCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
